# Generated by Django 4.0.2 on 2022-02-10 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='type_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTp', models.CharField(max_length=10)),
                ('percentageTp', models.PositiveIntegerField()),
                ('minimumTp', models.PositiveIntegerField()),
                ('maximumTp', models.PositiveBigIntegerField(null=True)),
                ('numberdayTp', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountWth', models.DecimalField(decimal_places=10, max_digits=15, unique=True)),
                ('dateWth', models.DateTimeField(auto_now_add=True)),
                ('receiverWth', models.CharField(max_length=100)),
                ('accountWth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.account')),
            ],
        ),
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=15, unique=True)),
                ('account_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.account')),
                ('type_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.type_plan')),
            ],
        ),
        migrations.CreateModel(
            name='deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountDep', models.DecimalField(decimal_places=10, max_digits=15, unique=True)),
                ('dateDep', models.DateTimeField(auto_now_add=True)),
                ('payerDep', models.CharField(max_length=100)),
                ('accountDep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user_a',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
    ]
