# Generated by Django 4.0.2 on 2022-02-16 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 2, 16, 16, 26, 57, 486993, tzinfo=utc), max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='refferal_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amountDep',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amountWth',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
