# Generated by Django 4.0.2 on 2022-02-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checkbox',
            field=models.BooleanField(default=True),
        ),
    ]
