# Generated by Django 4.0.2 on 2022-02-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_account_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_plan',
            name='maximumTp',
            field=models.PositiveBigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='type_plan',
            name='minimumTp',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='type_plan',
            name='nameTp',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='type_plan',
            name='percentageTp',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
