# Generated by Django 4.0.2 on 2022-04-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='statusDep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_dad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='dashboard.user'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='statusWth',
            field=models.BooleanField(default=False),
        ),
    ]
