# Generated by Django 4.0.2 on 2022-04-12 10:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_deposit_statusdep_user_user_dad_withdrawal_statuswth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/dashboard/images/avatar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_dad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='dashboard.user'),
        ),
    ]
