# Generated by Django 4.0.2 on 2022-04-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_user_image_alter_user_user_dad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(upload_to='static/dashboard/images/avatar'),
        ),
    ]
