# Generated by Django 4.0.4 on 2022-04-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_plan',
            name='maximumTp',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
