# Generated by Django 4.0.4 on 2022-04-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_type_plan_maximumtp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='static/dashboard/images/avatar'),
        ),
    ]
