# Generated by Django 4.0.4 on 2022-08-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_user_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name': 'Deposit', 'verbose_name_plural': 'Deposits'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Invest', 'verbose_name_plural': 'Invests'},
        ),
        migrations.AlterModelOptions(
            name='type_plan',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Plans'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'verbose_name': 'Withdrawal', 'verbose_name_plural': 'Withdrawals'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amountDep',
            field=models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='dateDep',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payerDep',
            field=models.CharField(max_length=100, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='statusDep',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=15, unique=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='type_plan',
            name='maximumTp',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Maximum'),
        ),
        migrations.AlterField(
            model_name='type_plan',
            name='minimumTp',
            field=models.PositiveIntegerField(unique=True, verbose_name='Minimum'),
        ),
        migrations.AlterField(
            model_name='type_plan',
            name='nameTp',
            field=models.CharField(max_length=10, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='type_plan',
            name='numberdayTp',
            field=models.PositiveIntegerField(verbose_name='Number of Days'),
        ),
        migrations.AlterField(
            model_name='type_plan',
            name='percentageTp',
            field=models.PositiveIntegerField(unique=True, verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='refferal_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Refferal Bonus'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amountWth',
            field=models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='dateWth',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='receiverWth',
            field=models.CharField(max_length=100, verbose_name='Receiver Accont'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='statusWth',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
