# Generated by Django 4.0.4 on 2022-08-24 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_account_options_alter_deposit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountInvested', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Amount Invested')),
                ('dateStart', models.DateTimeField(auto_now_add=True, verbose_name='Started on')),
                ('dateEnd', models.DateTimeField(auto_now_add=True, verbose_name='Ending on')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('relatedAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.account')),
                ('type_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.type_plan')),
            ],
            options={
                'verbose_name': 'Current Invest',
                'verbose_name_plural': 'Current Invests',
            },
        ),
    ]
