# Generated by Django 4.0.4 on 2022-08-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_currentinvestment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='checkedDep',
            field=models.BooleanField(default=False, verbose_name='Checked'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='checkedWth',
            field=models.BooleanField(default=False, verbose_name='Checked'),
        ),
    ]
